name: exec crawl

on:
  schedule:
    - cron: 0 10 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install operating system dependencies
      run: npx playwright install-deps
    - name: Install deps
      run: yarn install
    - name: Run
      run: yarn start
